### PR TITLE
Style alert callouts

### PR DESCRIPTION
**Pull request by keanulee**

### CODE REVIEW

**Comment by arthurevans** [comment]
Very cool. My one concern is that the yellow text on white background is very hard to read. At a contrast ratio of 2.66:1, it fails the accessibility test by a good margin.

https://webaim.org/resources/contrastchecker/?fcolor=EA8600&bcolor=FFFFFF

If we're going to add this to the other sites as well, I'd love a Tip style (lightbulb icon, maybe some color of green).

**Comment by yuinchien** [comment]
Let's update the warning text color to **#E42B00**, at 16px the contrast ratio will be 4.52 (AA compliant). Thanks!

chip

**Comment by keanulee** [comment]
Much better now, thanks!
image

**Comment by arthurevans** [comment]
Sold!

**Pull request merged**
